* 自學科學家系的日常入坑 spacemacs
** introduction 
 自學大學科學家系


  以成為科學家為目標，研究這個複雜的世界，學習世界運轉的原理之餘，玩著各種有趣的實作。
  為了完成更完整更自由的科學學習計畫，選擇拋棄學歷，開始了以網路世界為舞台的自學大學科學家系
  
  scientist department of self-study university
  For the quest of becoming a scientist , researching the complex world , simultanously studying the principle of the world manage to operate , fiddle all kind of interesting implement.
  In order to fullfill more complete and more free scientific research learning project , abandon the deploma , It's scientist department of self-study university 
  where the Internet world is stage began.

  在今年三月，選擇開始使用以 emacs 為基底打造的 spacemacs 專案，作為追尋目標的自學工具，
  使用 spacemacs 裡面整合豐富的套件，漸進的客制自學專案，增加研究與評估的效率。打造以學習實踐開放源使碼理念與科學精神為方向的環境。以網路世界為大學，在不同社群裡，追求現代科學家資格非日常的日常。

  March of this year , choose to start using emacs based spacemacs project , persuing target as a self-study tool.
  by versatile package inside spacemacs , step by step costumize self-study project , increasing research and review efficient ,
  for the purpose of building an enviromet of learning , practice open source idea and science spirit , internet world as colleg , in all diferent community ,
  ordinary of extrodinary quest for modern scientist qualification.
* speech structure
** science , college to self-study 
** emacs community to spacemacs
*** once orelly forget his emacs setting , now
** passion and star ring 
but everything has price 
pay less could gain big
and here is cram school
and then each different group 
** ring?
** org-mode GTD workflow
*** org-journal
*** org-capture 
*** projectile 
*** sync with magit 
** open source to government 
** publish through hexo and slide
** python and bot develop 
** COSCUP here you are 
